name: Test
 
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
 
jobs:
  phpcs:
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Test
      env:
        TEST_GITHUB_TOKEN: ${{ secrets.MAGENTO_PASSWORD }}
        TEST_SECRET: ${{ secrets.TEST }}
      run: |
        echo "test"
        echo ${{ secrets.TEST }}
      
