name: PHP CodeSniffer
 
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
 
jobs:
  phpcs:
    runs-on: ubuntu-latest
 
    strategy:
      matrix:
        php-version: [8.2,8.3]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use PHP ${{ matrix.php-version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: composer:v1

      - name: Test plugin installation
        run: |
          echo "{\"http-basic\":{\"repo.magento.com\":{\"username\":\"${MAGENTO_USERNAME}\",\"password\":\"${MAGENTO_PASSWORD}\"}}}" > auth.json
          composer install --prefer-dist
        env:
          CI: true
          MAGENTO_USERNAME: ${{ secrets.MAGENTO_USERNAME }}
          MAGENTO_PASSWORD: ${{ secrets.MAGENTO_PASSWORD }}

      - name: Code Sniffer
        run: vendor/bin/phpcs .

